# Generated by Django 6.0.2 on 2026-02-21 12:41

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=versatileimagefield.fields.VersatileImageField(
                upload_to="products/", verbose_name="Изображение"
            ),
        ),
    ]
